services:
  keycloak-db:
    image: postgres:16.2
    container_name: keycloak_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgresdata:/var/lib/postgresql/data
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.7
    container_name: keycloak
    command: ["start", "--verbose", "--import-realm"]
    environment:
      KC_DB: postgres
      KC_DB_ADDR: keycloak-db
      KC_DB_URL_DATABASE: ${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_PORT: 5432
      KC_DB_DRIVER: org.postgresql.Driver
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: "true"
      KC_HTTPS_KEY_STORE_FILE: "/etc/x509/https/keystore.p12"
      KC_HTTPS_KEY_STORE_PASSWORD: ${PS_KEYSTORE_PASSWORD}
      KC_HTTPS_PORT: "8443"
      KC_HTTPS_KEY_STORE_TYPE: "PKCS12"
      KC_HOSTNAME: darkmatterauth.ru
    volumes:
      - /etc/letsencrypt/live/darkmatterauth.ru:/etc/x509/https
      - ./realm-config.json:/opt/keycloak/data/import/realm-config.json
      - ./clients-config.json:/opt/keycloak/data/import/clients-config.json
    depends_on:
      - keycloak-db
    ports:
      - 8443:8443
    restart: always

volumes:
  postgresdata:
